### ISSUE TITLE
select.poll unsupported on OS X with built-in python

### ISSUE THREAD

**Issue by Abai** [crustymonkey/py-prefork-server#8]
I was wondering if it's possible to replace select.poll() with select.kqueue() as the polling is disabled in default OSX python installation, and is generally somewhat broken:

http://bugs.python.org/issue5154

Thanks for the great job!

**Comment by crustymonkey** [comment]
All right, I've got all the stupid stuff fixed.  I also fixed some idiosyncrasies that I found when testing on FreeBSD.  From my testing, it looks like I've got everything working correctly at this point.  Why don't you pull the updated dev_polling branch and give it a try.

**Comment by Abai** [comment]
Cool! I just tested it but select does not have the POLLIN attribute on OSX. I think it is being used in the child.py and manager.py:

  File "/Library/Python/2.7/site-packages/preforkserver/manager.py", line 122, in __init__
    self._poll = get_poller(select.POLLIN | select.POLLPRI)
AttributeError: 'module' object has no attribute 'POLLIN'

I am not sure if way you wanted to convert it to KQ_FILTER_READ/WRITE would work ...

Thanks again!

**Comment by crustymonkey** [comment]
Wow, that's really interesting, and seemingly broken...  This is the first system that I've come across where POLLIN isn't even defined.  I'm using those as a standard in terms of the universal polling interface.  However, I just pushed a hack that *should* fix that.  Give it a try.

**Comment by Abai** [comment]
It's the python that apple decided to supply, 3rd party python can be compiled with all the attributes. The system has POLLIN and also select.poll(), but I think they might have disabled it because it's supposedly buggy.

  File "/Library/Python/2.7/site-packages/preforkserver/poller.py", line 234, in __init__
    select.POLLOUT: select.KQ_FILTER_WRITE ,
AttributeError: 'module' object has no attribute 'POLLOUT'

Same problem in the poller so far ...

**Comment by crustymonkey** [comment]
Ah, I missed POLLOUT.  I just added that and pushed.  Hopefully these are the last missing items.

**Comment by crustymonkey** [comment]
I tested this on a friend's mac and the example code worked fine.  I've merged to the master branch and I'm closing this out.

**Comment by Abai** [comment]
Yes! All working fine. Thank you!

**Comment by crustymonkey** [comment]
Great, glad to hear it!
